Milestone 3 - Friendships v2
John-Arboleda/ror-social-scaffold pull request #3
Opened 2021-09-20 02:43 UTC by John-Arboleda

This is the third milestone of the Social Media Project from the Ruby on Rails Module. Starting from the previous milestone, the friendship model and users associations were improved, in order to make friendships with 2 rows for mutual friendship.

2021-09-20 09:45 UTC, bini-i requested changes
# Status: Changes Required :yellow_circle:            
### Hello @John-Arboleda  :wave: 

Your project looks good and shows you have put a lot of effort into it. Kindly work on the following suggestions to further improve your project.

## Summary
- Sending and accepting friend requests works smoothly.
- Posts of user and approved friends can only be seen.
- You have included add_reverse_friendship to establish a two-way friendship.

Kindly work on the following suggestions to further improve your project
## Optional suggestions
-   [_OPTIONAL_]

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

#### If you have any questions feel free to ask within the PR thread.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-09-20 09:45 UTC, bini-i commented on app/models/friendship.rb
> +  end
- [ ] It is good to create a reverse record of friendship once it is approved, but kindly make sure to also reverse sender_id and receiver_id in the new record.
```
eg: #1=> sender_id: 1, receiver_id: 2
      #2=> sender_id: 2, receive_id: 1
```

2021-09-20 09:45 UTC, bini-i commented on app/models/user.rb
> +  end
- [ ] Once you update the friendship model to record a reverse of every friendship, you can take advantage of it to get friends of a user by using one column (user_id)  with a status of true. Currently, you are checking both columns(user_id and friend_id), which results in a greater number of queries and performs less efficiently.

2021-09-21 02:35 UTC, e71az approved these changes
## Status:  Approved 🟢

Hi, @John-Arboleda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-09-21 11:56 UTC, merged